/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Have
 */
public class MenuFold extends javax.swing.JFrame {
    
    String line;
    List<String[]> listdata = new ArrayList<>();    
    List<String[]> listdatafuzzy = new ArrayList<>();
    private float age,kelas,direct_bilirubin, albumin, albumin_globulin_ratio, total_protiens, total_bilirubin, alamine_aminotransferase, aspartate_aminotransferase, alkaline_phosphotase;
    private String gender;
    double totalpi,totalni,anakpositif,anaknegatif,mudapositif,mudanegatif,dewasapositif,dewasanegatif,tbnormalpositif,
                  tbnormalnegatif,tbabnormalpositif,tbabnormalnegatif,dbnormalpositif,dbnormalnegatif,
                  dbabnormalpositif,dbabnormalnegatif,apnormalpositif,apnormalnegatif,apabnormalnegatif,apabnormalpositif,
                  aanormalpositif,aanormalnegatif,aaabnormalpositif,aaabnormalnegatif,asnormalpositif,asnormalnegatif,
                  asabnormalpositif,asabnormalnegatif,tprendahpositif,tprendahnegatif,
                  tpnormalnegatif,tpnormalpositif,tptinggipositif,tptingginegatif,
                  abrendahpositif,abrendahnegatif,abnormalpositif,abnormalnegatif,abtinggipositif,
                  abtingginegatif,agbnormalpositif,agbnormalnegatif,agbabnormalpositif,agbabnormalnegatif;
     double entropyklas,entropyanak,entropymuda,entropydewasa,entropytbnormal,entropytbabnormal,
                  entropydbnormal,entropydbabnormal,entropyapnormal,entropyapabnormal,entropyaanormal,entropyaaabnormal,
                  entropyasnormal,entropyasabnormal,entropytprendah,entropytpnormal,entropytptinggi,entropyabrendah,
                  entropyabnormal,entropyabtinggi,entropyabgnormal,entropyabgabnormal;
     double gainage,gaintb,gaindb,gainap,gainaa,gainas,gaintp,gainab,gainabg;
    Fuzzy c = new Fuzzy();
     
    /**
     * Creates new form MenuFold
     */
    public MenuFold() {
        initComponents();
        
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fold 1");

        jLabel2.setText("Fold 2");

        jLabel3.setText("Fold 3");

        jLabel4.setText("Fold 4");

        jLabel5.setText("Fold 5");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Training", "Testing" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Training", "Testing" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Training", "Testing" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Training", "Testing" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Training", "Testing" }));

        jLabel6.setText("Fold 6");

        jLabel7.setText("Fold 7");

        jLabel8.setText(" Fold 8");

        jLabel9.setText("Fold 9");

        jLabel10.setText("Fold 10");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Training", "Testing" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Training", "Testing" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Training", "Testing" }));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Training", "Testing" }));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Training", "Testing" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });

        jLabel12.setText("θr :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel13.setText("θn :");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Update Fold");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inputTeta();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed
    private void updateFold1(){
        Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        if (number == 0){
            number = 1;
        }
        if(jComboBox1.getSelectedIndex() == 0){
            String fold = "1";
            String status = "Training";
            updateDataFold(fold,status,number);
        }else{
            String fold = "1";            
            String status = "Testing";
            updateDataFold(fold,status,number);
        }
    }
   private void updateFold2(){
       Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        if(jComboBox2.getSelectedIndex() == 0){
            String fold = "2";
            String status = "Training";
            updateDataFold(fold,status,number);
        }else{
            String fold = "2";            
            String status = "Testing";
            updateDataFold(fold,status,number);
        }
    }
   private void updateFold3(){
       Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        if(jComboBox3.getSelectedIndex() == 0){
            String fold = "3";
            String status = "Training";
            updateDataFold(fold,status,number);
        }else{
            String fold = "3";            
            String status = "Testing";
            updateDataFold(fold,status,number);
        }
    }
   
   private void updateFold4(){
       Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        if(jComboBox4.getSelectedIndex() == 0){
            String fold = "4";
            String status = "Training";
            updateDataFold(fold,status,number);
        }else{
            String fold = "4";            
            String status = "Testing";
            updateDataFold(fold,status,number);
        }
    }
   
   private void updateFold5(){
       Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        if(jComboBox5.getSelectedIndex() == 0){
            String fold = "5";
            String status = "Training";
            updateDataFold(fold,status,number);
        }else{
            String fold = "5";            
            String status = "Testing";
            updateDataFold(fold,status,number);
        }
    }
   
   private void updateFold6(){
       Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        if(jComboBox6.getSelectedIndex() == 0){
            String fold = "6";
            String status = "Training";
            updateDataFold(fold,status,number);
        }else{
            String fold = "6";            
            String status = "Testing";
            updateDataFold(fold,status,number);
        }
    }
   
   private void updateFold7(){
       Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        if(jComboBox7.getSelectedIndex() == 0){
            String fold = "7";
            String status = "Training";
            updateDataFold(fold,status,number);
        }else{
            String fold = "7";            
            String status = "Testing";
            updateDataFold(fold,status,number);
        }
    }
   
   private void updateFold8(){
       Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        if(jComboBox8.getSelectedIndex() == 0){
            String fold = "8";
            String status = "Training";
            updateDataFold(fold,status,number);
        }else{
            String fold = "8";            
            String status = "Testing";
            updateDataFold(fold,status,number);
        }
    }
   
   private void updateFold9(){
       Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        if(jComboBox9.getSelectedIndex() == 0){
            String fold = "9";
            String status = "Training";
            updateDataFold(fold,status,number);
        }else{
            String fold = "9";            
            String status = "Testing";
            updateDataFold(fold,status,number);
        }
    }
   
   private void updateFold10(){
       Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        if(jComboBox10.getSelectedIndex() == 0){
            String fold = "10";
            String status = "Training";
            updateDataFold(fold,status,number);
        }else{
            String fold = "10";            
            String status = "Testing";
            updateDataFold(fold,status,number);
        }
    }
   public void insertDataFold(){
       Integer number;
        number = 0;
        Menu2 mn = new Menu2();
        number = mn.numProses();
        number = number + 1;
        java.sql.Connection conn=(Connection)Koneksi.configDB();
        try {
            String sql ="insert into prosesfold (age,gender,direct_bilirubin,alkaline_phosphotase,alamine_aminotransferase,aspartate_aminotransferase,total_protiens,total_bilirubin,albumin,albumin_and_globulin_ratio,fold,dataset,prosespenelitian) "
                    + "select age,gender,direct_bilirubin,alkaline_phosphotase,alamine_aminotransferase,aspartate_aminotransferase,total_protiens,total_bilirubin,albumin,albumin_and_globulin_ratio,fold,dataset,"+number+" from "
                    + "bahanmentah ";
           java.sql.PreparedStatement run=conn.prepareStatement(sql);
           System.out.println(sql);
            run.execute();
       }catch (Exception e) {
        }finally{
            try {
                if (conn !=null)
                    conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(MenuFold.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
   }
    public void updateDataFold(String fold, String status,Integer number){
        try {
            String sql ="UPDATE prosesfold SET status = '"+status+"' WHERE fold = '"+fold+"' and prosespenelitian = "+number+"";
            
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            conn.close();
        } catch (Exception e) {
        }
    }
    private void inputTeta(){
         java.sql.Connection conn=(Connection)Koneksi.configDB();
         Integer number;
        Menu2 mn = new Menu2();
        number = mn.numProses();
          if(number == 0){
              number = 1;
          }
       try{
           int tetar,tetan1 ;
           double tetan,tetan2,ctetan,ctetan2,ctetan3;
           tetan1 = 0;
           ctetan2 = 0;
           tetar = Integer.parseInt(jTextField1.getText());
           //tetan = Integer.parseInt(jTextField2.getText());
           ctetan = Integer.parseInt(jTextField2.getText());
           System.out.println(ctetan);
           String sql1 = "select count(idbahanmentah) from bahanmentah";
            java.sql.Statement stm1=conn.createStatement();
            java.sql.ResultSet res1=stm1.executeQuery(sql1);
            while(res1.next()){ 
              tetan1 = Integer.parseInt(res1.getString(1));
            }
            System.out.println(tetan1);
            tetan2 = ctetan/100;
            System.out.println(tetan2);
            tetan =tetan1*tetan2;
            System.out.println(tetan);
            tetan2 = tetan1/10;
            System.out.println(tetan2);
            if(ctetan2 <= tetan){
              String sql = "Insert into result(type,keytable,`value`,prosespenelitian) values ('teta','tetar','"+tetar+"',"+number+"),('teta','tetan','"+ctetan+"',"+number+")";
            java.sql.PreparedStatement run=conn.prepareStatement(sql);
            System.out.println(sql);
            run.execute();
            insertDataFold();
            updateFold1();
            updateFold2();
            updateFold3();
            updateFold4();
            updateFold5();
            updateFold6();
            updateFold7();
            updateFold8();
            updateFold9();
            updateFold10();
            JOptionPane.showMessageDialog(null, "Proses Penentunan Fold Berhasil. Silahkan pilih hitung fold, entropy dan gain");
            this.setVisible(false);
            Menu2 page=new Menu2();
            page.setBounds(400, 400, 600, 600);
            page.setVisible(true);
              
            }else{
                JOptionPane.showMessageDialog(null, "Nilai Teta N Terlalu Besar, Masukkan Angka Lebih Kecil");
            }
       }catch (Exception e) {
        }finally{
            try {
                if (conn !=null)
                    conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(MenuFold.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
  
    private void simpan(String[] a){
        try {
            BufferedWriter out = new BufferedWriter(new FileWriter("simpan.txt"));
            for(int i=0; i<a.length; i++) {
                out.write(a[i]);
                out.newLine();
            }
            out.close();
        }
        catch (IOException ex) {
            System.out.println("");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFold().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
